login screen front end issue
WrippleFoss/mentorFix pull request #232
Opened 2020-04-28 07:57 UTC by NikitaMasand

Following are the ss of the login page:
<img width="960" alt="mf1" src="https://user-images.githubusercontent.com/43334750/80462216-01e0f680-8954-11ea-82a1-ceffff3e5cb4.PNG">
<img width="960" alt="mf2" src="https://user-images.githubusercontent.com/43334750/80462233-086f6e00-8954-11ea-9de2-de4fd1e435a1.PNG">

2020-04-28 08:58 UTC, NikitaMasand commented
@abhishek71994  please review

2020-04-28 12:16 UTC, abhishek71994 approved these changes
Looks good to me. Just change the `px` to `rem`. As `rem` depends on the relative size of 16px. Pixel can be different for different screens to `rem` helps keep the styling consistent

2020-04-28 12:16 UTC, abhishek71994 commented on src-view/assets/styles/LoginView.module.scss
> +            width: 300px;
Change the `px` to `rem` please

2020-04-29 13:00 UTC, NikitaMasand commented on src-view/assets/styles/LoginView.module.scss
> +            width: 300px;
got it. changed it

2020-04-29 13:00 UTC, NikitaMasand commented
@abhishek71994 please check. I have changed the dimensions to rem as suggested.

2020-04-29 13:13 UTC, abhishek71994 requested changes

2020-04-29 13:13 UTC, abhishek71994 commented on src-view/assets/styles/LoginView.module.scss
> +            font-size: 14px;
In all the files I mean.

2020-04-29 13:13 UTC, abhishek71994 commented on src-view/assets/styles/LoginView.module.scss
> +            font-size: 14px;
Like all px's except maybe `border-radius`

2020-04-29 13:33 UTC, NikitaMasand commented
updated ss after changes:
<img width="950" alt="mf1" src="https://user-images.githubusercontent.com/43334750/80601888-08eb3000-8a4c-11ea-890b-1b7d46c441d2.PNG">
<img width="946" alt="mf2" src="https://user-images.githubusercontent.com/43334750/80601903-0dafe400-8a4c-11ea-84ab-b76eb8d8e632.PNG">

2020-04-29 13:35 UTC, abhishek71994 approved these changes

2020-04-29 13:35 UTC, merged